name: E2E Test

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "00 16 * * *"
  workflow_dispatch:

jobs:
  E2E_Linux_Ubuntu_run:
    permissions:
      checks: write
    name: Regular Check Linux (ubuntu) 
    runs-on: ubuntu-latest
    steps:
      - name: Geting repo files
        uses: actions/checkout@v4

      - run: echo "Setting up the Environment"
      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn -Dtest="RegisterationTest.SignupTestCase" test -DbrowserName="chrome" -DheadlessExecution="true" 
      - name: Allure Report
        run: mvn allure:report
      - name: Upload Allure Report
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: chrome
          path: target/site/allure-maven-plugin/index.html
      
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:      
          name: Tests Report Ubuntu
          path: 'target/surefire-reports/TEST-*.xml'      
          reporter: java-junit

  #job2 WINDOWS
  E2E_Windows_run:
    permissions:
      checks: write
    name: Regular Check Windows machine
    runs-on: windows-latest
    steps:
      - name: Geting repo files
        uses: actions/checkout@v4

    # environment
      - run: echo "Setting up the Environment"
      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn -Dtest="RegisterationTest.SignupTestCase" test -DbrowserName="chrome" -DheadlessExecution="true" 
      - name: Allure Report
        run: mvn allure:report
      - name: Upload Allure Report
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: target/site/allure-maven-plugin/index.html
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:      
          name: Tests Report Windows
          path: 'target/surefire-reports/TEST-*.xml'      
          reporter: java-junit
