name: E2E Test

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "00 3 * * 2,3"
  workflow_dispatch:
    inputs:
      TC_Class_Name:
        description: 'Specify the name of the test class to execute'
        required: false
        default: 'TC1RegisterUser'
      Browser_Name_Windows:
        description: "determine the browser on which the test cases will be executed in windows"
        required: true
        default: 'chrome'
        type: choice
        options:
          - 'firefox'
          - 'edge'
          - 'chrome'
      Browser_headless_Windows:
        description: "Select whether to run the test cases in headless mode "
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

      Browser_Name_Ubuntu:
        description: "determine the browser on which the test cases will be executed in Ubunto"
        required: true
        default: 'chrome'
        type: choice
        options:
          - 'firefox'
          - 'edge'
          - 'chrome'
     
      Browser_headless_Ubuntu:
        description: "Will the browser run TC headless on Ubuntu"
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

      CustomeInstructureUbuntu:
        description: 'Custome Instructionsfor modifying properties -DpropertyName="value" or adding --flag '
        required: false
        default: ''

jobs:
  E2E_Linux_Ubuntu_run:
    permissions:
      checks: write
    name: Regular Check Linux (ubuntu) machine
    runs-on: ubuntu-latest
    steps:
      - name: Geting repo files
        uses: actions/checkout@v4

      - run: echo "Setting up the Environment"
      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn -Dtest="automationexercise.test.${{ github.event.inputs.TC_Class_Name }}" test -Dbrowser="${{ github.event.inputs.Browser_Name_UbuntuMachine }}" -Dheadless=${{ github.event.inputs.Browser_headless_UbuntuMachine }} ${{ github.event.inputs.CustomeInstructureUbuntu }}
      - name: Allure Report
        run: mvn allure:report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ github.event.inputs.Browser_Name_UbuntuMachine }}_allure-results_Ubuntu
          path: target/site/allure-maven-plugin/index.html
      
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:      
          name: Tests Report Ubuntu
          path: 'target/surefire-reports/TEST-*.xml'      
          reporter: java-junit

  #job2 WINDOWS
  E2E_Windows_run:
    permissions:
      checks: write
    name: Regular Check Windows machine
    runs-on: windows-latest
    steps:
      - name: Geting repo files
        uses: actions/checkout@v4

    # environment
      - run: echo "Setting up the Environment"
      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn -Dtest="automationexercise.test.${{ github.event.inputs.TC_Class_Name }}" test -Dbrowser="${{ github.event.inputs.Browser_Name_WindowsMachine }}" -Dheadless=${{ github.event.inputs.Browser_headless_WindowsMachine }}
      - name: Allure Report
        run: mvn allure:report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ github.event.inputs.Browser_Name_WindowsMachine }}_allure-results_Windows
          path: target/site/allure-maven-plugin/index.html
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:      
          name: Tests Report Windows
          path: 'target/surefire-reports/TEST-*.xml'      
          reporter: java-junit
